### ISSUE TITLE
Can't configure the url to go to after clicking the notification

### ISSUE THREAD

**Issue by hisem** [Graffino/Browser-Update#4]
Hi @zenopopovici and thanks for your work.

It seems like the url we can configure using: 
```
var $buoop = {
  [...]
        url: null,         // the url to go to after clicking the notification
  [...]
};
```

is always overridden by whatbrowser.org here (in browser-update.js, lines 18 & 19):

```
var burl = "//whatbrowser.org";
op.url = burl;
```

When commenting out these lines, my own target url defined in $buoop is used, if not, the user is always redirected to whatbrowser.org...

Is this on purpose?

**Comment by zenopopovici** [comment]
@hisem No :). I'll look into it. I'm just maintaining this but not actualy using it.

**Comment by hisem** [comment]
@zenopopovici Haha ok, no worries, thanks for your time if you get around to fixing it. I just extracted the .js file and made it fit my needs for this project, so there's no rush.

Do you use some alternative for this now? I looked into outdatedbrowser.com but it only seems to handle outdated IE browsers, and is not very customisable.

**Comment by zenopopovici** [comment]
@hisem Not really. http://outdatedbrowser.com when needed. I hate it that it needs 2 files and a div and some JS. Don't really know why they've done it like that.

Isse fixed.

**Comment by hisem** [comment]
@zenopopovici Awesome, that was quick, thanks! Will check it out tomorrow.
